### DISCUSSION TITLE
4 Channel WiFi Relay

### DISCUSSION THREAD

**Discussion by martinarrieta** [codetheweb/tuyapi#504] [Q&A]
Hello, 

I have a [4 Channel WiFi Relay](https://www.amazon.com/dp/B089QD5CT6) and it works fine with the following configuration:

```yaml
  - host: 192.168.1.x
    device_id: xxxxxxxxxxxxxxx
    local_key: xxxxxxxxxxxxxxx
    friendly_name: WiFi switch-4CH
    protocol_version: "3.3"
    entities:
      - platform: switch
        friendly_name: Unused 1
        id: 1
      - platform: switch
        friendly_name: Unused 2
        id: 2
      - platform: switch
        friendly_name: Unused 3
        id: 3
      - platform: switch
        friendly_name: Front Gate
        id: 4
```

However, I was able to trigger relay 4 with the voice command "Turn on Front Gate" because for Alexa this is a "light switch", I'm not sure how can I change this platform to be able to trigger this with "Open Front Gate".

Thanks!
